# Generated by Django 4.0.3 on 2022-03-23 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_is_logged_in_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_logged_in',
            new_name='online',
        ),
    ]
