# Generated by Django 4.0.3 on 2022-03-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_key_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='key',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
