# Generated by Django 4.0.3 on 2022-03-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_key_user_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_page',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='online',
            field=models.BooleanField(default=True),
        ),
    ]
