# Generated by Django 4.0.3 on 2022-03-25 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_user_last_page_alter_user_online'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_page',
            new_name='current_page',
        ),
    ]
