# Generated by Django 4.0.3 on 2022-03-25 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_last_page_user_current_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_page',
            field=models.CharField(default='/chat', max_length=30),
        ),
    ]
