# Generated by Django 4.0.3 on 2022-03-26 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_user_email_alter_user_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='user_id',
        ),
        migrations.AddField(
            model_name='conversation',
            name='group',
            field=models.ManyToManyField(to='api.user'),
        ),
    ]
