# Generated by Django 4.0.3 on 2022-03-26 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_conversation_group_remove_conversation_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
