# Generated by Django 4.0.3 on 2022-03-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_conversation_name_alter_user_conversation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.CharField(default='change me', max_length=50),
        ),
    ]
