# Generated by Django 4.0.3 on 2022-03-27 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='users',
            field=models.ManyToManyField(to='api.user'),
        ),
    ]
