# Generated by Django 4.0.3 on 2022-03-27 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_conversation_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='users',
        ),
        migrations.AddField(
            model_name='conversation',
            name='group_name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
