# Generated by Django 4.0.3 on 2022-03-27 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_conversation_users_conversation_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='users',
            field=models.ManyToManyField(to='api.user'),
        ),
    ]
