# Generated by Django 4.0.3 on 2022-03-29 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_conversation_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Conversation',
        ),
    ]
