# Generated by Django 4.0.3 on 2022-03-29 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_delete_user_conversation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='name',
        ),
    ]
